# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: dependencies
    color: 0366d6
  - name: feature
    color: 84b6eb
  - name: enhancement
    color: f4c21d
  - name: deprecated
    color: f4c21d
  - name: tests
    color: 30cc62
  - name: documentation
    color: e6e6e6
  - name: internal
    color: e6e6e6
